apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: "[filebeat-]YYYY.MM.DD"
      timeField: "@timestamp"
      esVersion: "8.15.0"
      interval: "Daily"
      timeInterval: "10s"
      maxConcurrentShardRequests: 5
      logLevelField: ""
      logMessageField: "message"
    editable: true
    uid: Elasticsearch
