filebeat.inputs:
- type: syslog
  protocol.udp:
    host: "0.0.0.0:514"
  fields:
    service: "springboot-app"
  fields_under_root: true

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - dissect:
      tokenizer: "<%{priority}>%{timestamp} %{hostname} %{program}: %{message}"
      field: "message"
      target_prefix: "syslog"
  - decode_json_fields:
      fields: ["syslog.message"]
      target: ""
      overwrite_keys: true
      when:
        contains:
          syslog.message: "{"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-%{+yyyy.MM.dd}"
  template.enabled: false

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.enabled: false
setup.ilm.enabled: false

logging.level: debug
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644