name: CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

  docker-build-push:
    runs-on: ubuntu-latest
    needs: test-and-analyze
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/spring-boot-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME